---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "jackett.fullname" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}

data:
  TZ: "{{ .Values.tz }}"
  AUTO_UPDATE: "{{ .Values.auto_update }}"
  PUID: "{{ .Values.puid }}"
  PGID: "{{ .Values.pgid }}"
  UMASK: "022"


