---
apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "lidarr.fullname" . }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}

data:
  TZ: "{{ .Values.config.tz }}"
  PUID: "{{ .Values.config.puid }}"
  PGID: "{{ .Values.config.pgid }}"
  UMASK: "022"
