---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: music

spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: {{ .Values.volume.size }}