apiVersion: v1
kind: Service

metadata:
  name: {{ include "lidarr.fullname" . }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}

spec:
  ports:
    - name: {{ include "lidarr.fullname" . }}-service
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: gui

  selector:
    {{- include "lidarr.selectorLabels" . | nindent 4 }}

  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}