---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "lidarr.fullname" . }}
  labels:
    {{- include "lidarr.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: Recreate

  selector:
    matchLabels:
      {{- include "lidarr.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lidarr.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "lidarr.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}  

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: gui
              containerPort: 8686
              protocol: TCP

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "lidarr.fullname" . }}

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: {{ .Values.volume.subPath }}
            - name: music
              mountPath: /music
            - name: downloads
              mountPath: /downloads
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: usb-local
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""
