---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  strategy:
    type: Recreate

  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "sonarr.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: gui
              containerPort: 8989
              protocol: TCP

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          envFrom:
            - configMapRef:
                name: {{ include "sonarr.fullname" . }}

          volumeMounts:
            - name: data
              mountPath: /config
              subPath: {{ include "sonarr.fullname" . }}
            - name: tv-shows
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: usb-local
        - name: tv-shows
          persistentVolumeClaim:
            claimName: tv-shows
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""
