apiVersion: v1
kind: Secret

metadata:
  name: {{ include "tor.fullname" . }}
  labels:
    {{- include "tor.labels" . | nindent 4 }}

data:
  TOR_CONTROL_PASSWORD: "{{ .Values.config.control.password | b64enc }}"