apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "tor.fullname" . }}
  labels:
    {{- include "tor.labels" . | nindent 4 }}
    
data:
  PUID: "{{ .Values.puid }}"
  PGID: "{{ .Values.pgid }}"
  TOR_CONFIG_OVERWRITE: "{{ .Values.config.configOverwrite }}"
  TOR_LOG_CONFIG: "{{ .Values.config.logConfig }}"
  TOR_REMOVE_FILE_LOCK: "{{ .Values.config.torRemoveFileLock }}"
  TOR_PROXY: "{{ .Values.config.proxy.enable }}"
  TOR_PROXY_SOCKET: "{{ .Values.config.proxy.socket }}"
  TOR_PROXY_PORT: "0.0.0.0:{{ .Values.config.proxy.port }}"
  TOR_PROXY_ACCEPT: "{{ .Values.config.proxy.accept }}"
  TOR_CONTROL: "{{ .Values.config.control.enable }}"
  TOR_CONTROL_PORT: "0.0.0.0:{{ .Values.config.control.port }}"
  TOR_CONTROL_SOCKET: "0.0.0.0:{{ .Values.config.control.socket }}"
  TOR_CONTROL_COOKIE: "{{ .Values.config.control.cookie }}"
  TOR_SERVICE: "{{ .Values.config.hiddenServices.enable }}"
  TOR_SERVICE_HOSTS: "{{ .Values.config.hiddenServices.hosts }}"
  TOR_SERVICE_HOSTS_CLIENTS: "{{ .Values.config.hiddenServices.clients }}"