apiVersion: v1
kind: Service

metadata:
  name: {{ include "tor.fullname" . }}
  labels:
    {{- include "tor.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Namespace }}
    
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - port: {{ .Values.service.port.proxy }}
      targetPort: proxy
      protocol: TCP
      name: proxy
    - port: {{ .Values.service.port.control }}
      targetPort: control
      protocol: TCP
      name: control
  
  selector:
    {{- include "tor.selectorLabels" . | nindent 4 }}
