apiVersion: v1
kind: Secret

metadata:
  name: {{ include "bitcoin-core.fullname" . }}
  labels:
    {{- include "bitcoin-core.labels" . | nindent 4 }}

data:
  RPC_USER:  "{{ .Values.config.rpcUser | b64enc }}"
  RPC_PASSWORD:  "{{ .Values.config.rpcPassword | b64enc }}"
  TOR_PASSWORD: "{{ .Values.config.torPassword | b64enc }}"