apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ include "bitcoin-core.fullname" . }}
  labels:
    {{- include "bitcoin-core.labels" . | nindent 4 }}
    
spec:
  capacity:
    storage: {{ .Values.volume.size }}

  accessModes: ["{{ .Values.volume.accessModes }}"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volume.storageClassName }}

  mountOptions:
    - hard
    - nfsvers=3

  claimRef:
    name: {{ include "bitcoin-core.fullname" . }}
    namespace: {{ .Release.Namespace }}
    
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
    readOnly: false