apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "bitcoin-core.fullname" . }}
  labels:
    {{- include "bitcoin-core.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: {{ .Values.volume.size }}