apiVersion: v1
kind: PersistentVolume

metadata:
  name: usb-local

spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  accessModes: 
    - ReadWriteMany
    
  capacity:
    storage: 50Gi

  claimRef: 
    name: usb-local
    namespace: {{ .Release.Namespace }}

  local:
    path: /media/usb-local

  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1