apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: usb-local
  namespace: {{ .Release.Namespace }}

spec:
  storageClassName: local-storage
  accessModes: 
    - ReadWriteMany
    
  resources:
    requests:
      storage: 50Gi