apiVersion: v1
kind: Secret

metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}

data:
  OPENVPN_PROVIDER: {{ .Values.vpn.provider | b64enc }}
  OPENVPN_USERNAME: {{ .Values.vpn.username | b64enc }}
  OPENVPN_PASSWORD: {{ .Values.vpn.password | b64enc }}
  TRANSMISSION_RPC_USERNAME: {{ .Values.transmission.username | b64enc }}
  TRANSMISSION_RPC_PASSWORD: {{ .Values.transmission.password | b64enc }}