apiVersion: v1
kind: PersistentVolume

metadata:
  name: downloads

spec:
  capacity:
    storage: {{ .Values.volume.size.downloads }}

  accessModes: ["{{ .Values.volume.accessModes }}"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volume.storageClassName.downloads }}

  mountOptions:
    - hard
    - nfsvers=3

  claimRef: 
    name: downloads
    namespace: {{ .Release.Namespace }}

  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path.downloads }}
    readOnly: false