apiVersion: v1
kind: PersistentVolume

metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}

spec:
  capacity:
    storage: {{ .Values.volume.size.transmission }}

  accessModes: ["{{ .Values.volume.accessModes }}"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volume.storageClassName.transmission }}

  mountOptions:
    - hard
    - nfsvers=3

  claimRef: 
    name: {{ include "transmission.fullname" . }}
    namespace: {{ .Release.Namespace }}

  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path.transmission }}
    readOnly: false