apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.volume.storageClassName.transmission }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: {{ .Values.volume.size.transmission }}