apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: downloads

spec:
  storageClassName: {{ .Values.volume.storageClassName.downloads }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: {{ .Values.volume.size.downloads }}