---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "transmission.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "transmission.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - secretRef:
                name: {{ include "transmission.fullname" . }}
            - configMapRef:
                name: {{ include "transmission.fullname" . }}

          ports:
            - name: gui
              containerPort: 9091
              protocol: TCP
              
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: downloads
              mountPath: /data/downloads
            - name: data
              mountPath: /data/transmission-home
              subPath: {{ .Values.volume.subPath.transmission}}
            - name: tunnel
              mountPath: /dev/net/tun
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true

      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "transmission.fullname" . }}
        - name: tunnel
          hostPath:
            path: /dev/net/tun
            type: ""
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""