apiVersion: v1
kind: Secret

metadata:
  name: {{ include "btc-rpc-explorer.fullname" . }}
  labels:
    {{- include "btc-rpc-explorer.labels" . | nindent 4 }}

data:
  BITCOIND_USER: "{{ .Values.bitcoinCore.username | b64enc }}"
  COOKIE_SECRET: "{{ .Values.explorer.cookieSecret | b64enc }}"
  BITCOIND_PASS: "{{ .Values.bitcoinCore.password | b64enc  }}"
  BASIC_AUTH_PASSWORD: "{{ .Values.explorer.password | b64enc  }}"