apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "btc-rpc-explorer.fullname" . }}
  labels:
    {{- include "btc-rpc-explorer.labels" . | nindent 4 }}
    
data:
  PUID: "{{ .Values.puid }}"
  PGID: "{{ .Values.pgid }}"
  OVERWRITE_CONFIG: "{{ .Values.explorer.overwriteConfig }}"
  LOG_CONFIG: "{{ .Values.explorer.logConfig }}"
  DEBUGGER: "{{ .Values.explorer.debug }}"
  BASEURL: "{{ .Values.explorer.baseURL }}"
  COIN: "{{ .Values.explorer.coin }}"
  HOST: "{{ .Values.explorer.host }}"
  PORT: "{{ .Values.explorer.port }}"
  BITCOIND_COOKIE: "{{ .Values.bitcoinCore.cookieLocation }}"
  BITCOIND_HOST: "{{ .Values.bitcoinCore.host }}"
  BITCOIND_PORT: "{{ .Values.bitcoinCore.port }}"
  BITCOIND_RPC_TIMEOUT: "{{ .Values.bitcoinCore.timeout }}"
  ADDRESS_API: "{{ .Values.explorer.addressAPI }}"
  ELECTRUM_SERVERS: "{{ .Values.electrum.servers }}"
  ELECTRUM_TXINDEX: "{{ .Values.electrum.txIndex }}"
  RPC_CONCURRENCY: "{{ .Values.bitcoinCore.concurrency }}"
  NO_INMEMORY_RPC_CACHE: "{{ .Values.bitcoinCore.disableInMemory }}"
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  DEMO: "{{ .Values.explorer.demo }}"
  SLOW_DEVICE_MODE: "{{ .Values.explorer.slowDevice }}"
  PRIVACY_MODE: "{{ .Values.explorer.privacyMode }}"
  NO_RATES: "{{ .Values.explorer.noRates }}"
  SSO_TOKEN_FILE: "{{ .Values.sso.tokenFile }}"
  SSO_LOGIN_REDIRECT_URL:  "{{ .Values.sso.redirect }}"
  RPC_ALLOWALL: "{{ .Values.bitcoinCore.allowAll }}"
  RPC_BLACKLIST: "{{ .Values.bitcoinCore.blackList }}"
  GANALYTICS_TRACKING: "{{ .Values.explorer.keys.ganalytics }}"
  SENTRY_URL: "{{ .Values.explorer.keys.sentry }}"
  IPSTACK_APIKEY: "{{ .Values.explorer.keys.ipStack }}"
  MAPBOX_APIKEY: "{{ .Values.explorer.keys.mapBox }}"
  FILESYSTEM_CACHE_DIR: "{{ .Values.explorer.cacheDir }}"
  PLAUSIBLE_ANALYTICS_DOMAIN: "{{ .Values.explorer.plausible.domain }}"
  PLAUSIBLE_ANALYTICS_SCRIPT_URL: "{{ .Values.explorer.plausible.scriptUrl }}"
  OLD_SPACE_MAX_SIZE: "{{ .Values.explorer.oldSpaceMaxSize }}"
  NOTXINDEX_SEARCH_DEPTH: "{{ .Values.explorer.nonTXIndexSearchDepth }}"
  UI_THEME: "{{ .Values.explorer.ui }}"
  UI_HOME_PAGE_LATEST_BLOCKS_COUNT: "{{ .Values.explorer.latestCount }}"
  UI_BLOCKS_PAGE_BLOCK_COUNT: "{{ .Values.explorer.pageCount }}"

