apiVersion: v1
kind: Service

metadata:
  name: {{ include "btc-rpc-explorer.fullname" . }}
  labels:
    {{- include "btc-rpc-explorer.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - port: {{ .Values.service.ports.gui }}
      targetPort: gui
      protocol: TCP
      name: gui

  selector:
    {{- include "btc-rpc-explorer.selectorLabels" . | nindent 4 }}
