apiVersion: v1
kind: PersistentVolume

metadata:
  name: books

spec:
  capacity:
    storage: {{ .Values.volume.size }}

  accessModes: ["{{ .Values.volume.accessModes }}"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.volume.storageClassName }}

  mountOptions:
    - hard
    - nfsvers=3

  claimRef:
    name: books
    namespace: {{ .Release.Namespace }}
    
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
    readOnly: false