---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: books
  labels:
    {{- include "readarr.labels" . | nindent 4 }}

spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes: ["{{ .Values.volume.accessModes }}"]
    
  resources:
    requests:
      storage: {{ .Values.volume.size }}