apiVersion: v1
kind: Service

metadata:
  name: {{ include "readarr.fullname" . }}
  labels:
    {{- include "readarr.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: gui
      protocol: TCP
      name: gui
      
  selector:
    {{- include "readarr.selectorLabels" . | nindent 4 }}
